<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
      <LangVersion>latestMajor</LangVersion>
      <NoWarn>1701;1702;IDE0051;CS0436</NoWarn>
	  <Configurations>Release;Debug</Configurations>
	  <RootNamespace>RobDriver</RootNamespace>
  </PropertyGroup>
    
  <ItemGroup>
    <Compile Remove="Weaver\**" />
    <EmbeddedResource Remove="Weaver\**" />
    <None Remove="Weaver\**" />
  </ItemGroup>
    
  <ItemGroup>
    <None Remove=".gitignore" />
  </ItemGroup>
    
  <ItemGroup>
	<PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="MMHOOK.RoR2" Version="2025.11.19" NoWarn="NU1701" />
    <PackageReference Include="R2API.ContentManagement" Version="1.0.10" />
    <PackageReference Include="R2API.Core" Version="5.2.0" />
    <PackageReference Include="R2API.DamageType" Version="1.1.7" />
    <PackageReference Include="R2API.Dot" Version="1.1.2" />
    <PackageReference Include="R2API.Language" Version="1.1.0" />
    <PackageReference Include="R2API.Networking" Version="1.0.4" />
    <PackageReference Include="R2API.Prefab" Version="1.1.1" />
    <PackageReference Include="R2API.RecalculateStats" Version="1.6.5" />
    <PackageReference Include="R2API.Skills" Version="1.0.4" />
    <PackageReference Include="R2API.Skins" Version="1.4.4" />
    <PackageReference Include="R2API.Sound" Version="1.0.3" />
    <PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.0-r.0" />
    <PackageReference Include="RoR2BepInExPack" Version="1.38.0" />
    <PackageReference Include="Rune580.Mods.RiskOfRain2.RiskOfOptions" Version="2.8.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AncientScepter">
      <HintPath>libs\AncientScepter.dll</HintPath>
    </Reference>
    <Reference Include="ClassicItemsReturns">
      <HintPath>libs\ClassicItemsReturns.dll</HintPath>
    </Reference>
    <Reference Include="HunkHud">
      <HintPath>..\..\..\SharedRef\HunkHud.dll</HintPath>
    </Reference>
    <Reference Include="HunkMod">
      <HintPath>libs\HunkMod.dll</HintPath>
    </Reference>
    <Reference Include="LostInTransit">
      <HintPath>libs\LostInTransit.dll</HintPath>
    </Reference>
    <Reference Include="RiskUI">
      <HintPath>libs\RiskUI.dll</HintPath>
    </Reference>
    <Reference Include="Starstorm2">
      <HintPath>libs\Starstorm2.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>libs\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call postbuild.bat $(TargetDir) $(AssemblyName)" />
  </Target>

</Project>
